module.exports = {
  options: [
    {
      type: "category",
      label: "Sources",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/sources"
        }
      ]
    },
    {
      type: "category",
      label: "Display",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/display"
        }
      ]
    },
    {
      type: "category",
      label: "Control",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/control"
        }
      ]
    }
  ]
}
