module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  ...require("./sidebars-options.js"),
  ...require("./sidebars-advanced.js"),
  ...require("./sidebars-api.js")
};
