module.exports = {
  docs: [
    {
      type: "autogenerated",
      dirName: "tutorials"
    }
  ],
  options: [
    {
      type: "category",
      label: "Sources",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/sources"
        }
      ]
    },
    {
      type: "category",
      label: "Environment",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/environment"
        }
      ]
    },
    {
      type: "category",
      label: "Control",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "options/control"
        }
      ]
    }
  ],
  advanced: [
    "advanced/Preset",
    "advanced/Test"
  ],
  events: [
    {
      type: "autogenerated",
      dirName: "events"
    }
  ],
  ar: [
    {
      type: "autogenerated",
      dirName: "ar"
    }
  ],
  ...require("./sidebars-api.js")
};
